# Generated by Django 4.2.11 on 2026-08-22 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sample_id", models.CharField(max_length=20, unique=True)),
                ("sampling_date", models.DateField()),
                (
                    "testing_status",
                    models.CharField(
                        choices=[
                            ("NOT_TESTED", "Not Tested"),
                            ("IN_TESTING", "In Testing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_TESTED",
                        max_length=20,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="materials.material",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
