import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function FPForm({type,close,state,update,notify}) {
  const [f,setF]=useState({productName:"",batchNo:"",batchSize:"",unit:"",mfgDate:"",expDate:"",sampleSize:"",date:today(),time:"",stages:[]});const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const submit=()=>{for(const [k,l] of Object.entries({productName:"Product Name",batchNo:"Batch No.",batchSize:"Batch Size",sampleSize:"Quantity of Sample",date:"Sampling Date",time:"Time of Sampling"}))if(!f[k])return notify(l+" is required.","error");const prefix={ "Finished Product":"FP","Semi-Finished Product":"SFP","Bulk":"BLK"}[type];const key={ "Finished Product":"fp","Semi-Finished Product":"sfp","Bulk":"blk"}[type];const sid=id(prefix,state.counters[key]);update(s=>{s.fpSamples.push({id:"FPSMP-"+Date.now(),sampleId:sid,productName:f.productName,productType:type,batchNo:f.batchNo,batchSize:f.batchSize,unit:f.unit,mfgDate:f.mfgDate,expDate:f.expDate,sampleSize:f.sampleSize,timeOfSampling:f.time,samplingDate:f.date,stages:f.stages,testingStatus:"Not Tested"});s.counters[key]++});close();notify(`${type} sample registered! ID: ${sid}`)};
  return <Modal title={`Register ${type} Sample`} sub={`${type} — New Sample Registration`} open onClose={close} wide footer={<><Button onClick={close}>Cancel</Button><Button variant="primary" onClick={submit}>✓ Register Sample</Button></>}><div className="form-grid"><div className="fsec">Product Information</div><Field label="Product Type"><Input value={type} readOnly/></Field><Field label="Sampling Date *"><Input value={f.date} onChange={v=>set("date",v)} type="date"/></Field><Field label="Time *"><Input value={f.time} onChange={v=>set("time",v)} type="time"/></Field><Field label="Product Name *"><Select value={f.productName} onChange={v=>set("productName",v)} options={state.opts.productName}/></Field><Field label="Batch No. *"><Input value={f.batchNo} onChange={v=>set("batchNo",v)}/></Field><Field label="Batch Size *"><Input value={f.batchSize} onChange={v=>set("batchSize",v)} type="number"/></Field><Field label="Unit"><Select value={f.unit} onChange={v=>set("unit",v)} options={state.opts.unit}/></Field><Field label="Manufacturing Date"><Input value={f.mfgDate} onChange={v=>set("mfgDate",v)} type="date"/></Field><Field label="Expiry Date"><Input value={f.expDate} onChange={v=>set("expDate",v)} type="date"/></Field><Field label="Quantity of Sample *"><Input value={f.sampleSize} onChange={v=>set("sampleSize",v)} type="number"/></Field><div className="fsec">Stage of Sample</div><Field full label="Select stages"><div className="checkbox-group">{["Local Market","UPA","F.M.A","Export to","For Toll"].map(x=><label key={x}><input type="checkbox" checked={f.stages.includes(x)} onChange={e=>set("stages",e.target.checked?[...f.stages,x]:f.stages.filter(y=>y!==x))}/>{x}</label>)}</div></Field></div></Modal>
}
