import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function Sampling({m,close,state,update,notify,open}) {
  const [f,setF]=useState({sampleSize:"",containers:"",sampler:"",storage:"",date:today()});const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const submit=()=>{for(const [k,l] of Object.entries({sampleSize:"Sample Size",containers:"Containers",sampler:"Sampler Name",storage:"Storage Condition",date:"Sampling Date"}))if(!f[k])return notify(l+" is required.","error");const sample={id:"SMP-"+Date.now(),sampleId:m.receiptId,materialId:m.id,materialName:m.materialName,receiptId:m.receiptId,supplierBatch:m.supplierBatch,supplier:m.supplier,manufacturer:m.manufacturer,expDate:m.expDate,warehouse:m.warehouse,location:m.location,unit:m.unit,receiptDate:m.receiptDate,batchSize:m.batchSize,mfgDate:m.mfgDate,sampleSize:f.sampleSize,containers:f.containers,sampler:f.sampler,storage:f.storage,samplingDate:f.date,testingStatus:"Not Tested"};update(s=>{s.samples.push(sample);const x=s.materials.find(x=>x.id===m.id);x.samplingStatus="Sampled";x.storageCondition=f.storage});close();open("label");notify("Sample recorded successfully!");};
  return <Modal title="Sampling Form" sub={`${m.receiptId} · ${m.materialName}`} open onClose={close} footer={<><Button onClick={close}>Cancel</Button><Button variant="primary" onClick={submit}>✓ Save & Preview Labels</Button></>}><div className="form-grid"><Field label="Sample ID"><Input value={m.receiptId} readOnly/></Field><Field label="Material Name"><Input value={m.materialName} readOnly/></Field><Field label="Sample Size *"><Input value={f.sampleSize} onChange={v=>set("sampleSize",v)} type="number"/></Field><Field label="Unit"><Input value={m.unit} readOnly/></Field><Field label="Containers Sampled *"><Input value={f.containers} onChange={v=>set("containers",v)} type="number"/></Field><Field label="Sampler Name *"><Input value={f.sampler} onChange={v=>set("sampler",v)}/></Field><Field label="Storage Condition *"><Select value={f.storage} onChange={v=>set("storage",v)} options={["Ambient (15–25°C)","Refrigerated (2–8°C)","Frozen (−20°C)","Protected from Light","Controlled Room Temperature"]}/></Field><Field label="Sampling Date *"><Input value={f.date} onChange={v=>set("date",v)} type="date"/></Field></div></Modal>
}
