import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function RegisterMaterial({close,state,update,notify}) {
  const [f,setF]=useState({materialName:"",category:"",supplier:"",manufacturer:"",countryOrigin:"",supplierBatch:"",mfgDate:"",expDate:"",batchSize:"",unit:"kg",packageType:"",numPackages:"",packageSize:"",warehouse:"",location:"",poNo:"",invNo:"",receiptDate:today(),receivedBy:""});
  const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const qty=(+f.numPackages||0)*(+f.packageSize||0)||"";
  const submit=()=>{for(const [k,l] of Object.entries({materialName:"Material Name",supplier:"Supplier",supplierBatch:"Supplier Batch No.",expDate:"Expiry Date",receiptDate:"Receipt Date",receivedBy:"Received By"}))if(!f[k])return notify(l+" is required.","error");const rid=id("RM",state.counters.rc);update(s=>{s.materials.push({id:"MAT-"+Date.now(),receiptId:rid,...f,totalQty:qty,status:"Quarantine",samplingStatus:"Not Sampled",qcStatus:"Pending",qcNumber:null,retestDate:null});s.counters.rc++});close();notify("Material registered successfully!");};
  return <Modal title="Register Incoming Material" sub={`Receipt ID: ${id("RM",state.counters.rc)}`} open onClose={close} wide footer={<><Button onClick={close}>Cancel</Button><Button variant="primary" onClick={submit}>✓ Register Material</Button></>}><div className="form-grid">
    <div className="fsec">Material Information</div><Field label="Material Name *"><Select value={f.materialName} onChange={v=>set("materialName",v)} options={state.opts.materialName}/></Field><Field label="Category"><Select value={f.category} onChange={v=>set("category",v)} options={state.opts.category}/></Field><Field label="Supplier *"><Select value={f.supplier} onChange={v=>set("supplier",v)} options={state.opts.supplier}/></Field><Field label="Manufacturer"><Select value={f.manufacturer} onChange={v=>set("manufacturer",v)} options={state.opts.manufacturer}/></Field><Field label="Country of Origin"><Input value={f.countryOrigin} onChange={v=>set("countryOrigin",v)} placeholder="e.g. Germany"/></Field><Field label="Supplier Batch No. *"><Input value={f.supplierBatch} onChange={v=>set("supplierBatch",v)} placeholder="BATCH-2026-001"/></Field>
    <div className="fsec">Dates & Batch</div><Field label="Manufacturing Date"><Input value={f.mfgDate} onChange={v=>set("mfgDate",v)} type="date"/></Field><Field label="Expiry Date *"><Input value={f.expDate} onChange={v=>set("expDate",v)} type="date"/></Field><Field label="Batch Size"><Input value={f.batchSize} onChange={v=>set("batchSize",v)} type="number"/></Field><Field label="Unit"><Select value={f.unit} onChange={v=>set("unit",v)} options={state.opts.unit}/></Field>
    <div className="fsec">Packaging</div><Field label="Type of Packages"><Select value={f.packageType} onChange={v=>set("packageType",v)} options={state.opts.packageType}/></Field><Field label="No. of Packages"><Input value={f.numPackages} onChange={v=>set("numPackages",v)} type="number"/></Field><Field label="Package Size"><Input value={f.packageSize} onChange={v=>set("packageSize",v)} type="number"/></Field><Field label="Total Quantity (auto)"><Input value={qty} readOnly/></Field>
    <div className="fsec">Warehouse & Receipt</div><Field label="Warehouse"><Select value={f.warehouse} onChange={v=>set("warehouse",v)} options={state.opts.warehouse}/></Field><Field label="Location"><Input value={f.location} onChange={v=>set("location",v)} placeholder="Shelf A-3"/></Field><Field label="PO No."><Input value={f.poNo} onChange={v=>set("poNo",v)}/></Field><Field label="Invoice No."><Input value={f.invNo} onChange={v=>set("invNo",v)}/></Field><Field label="Receipt Date *"><Input value={f.receiptDate} onChange={v=>set("receiptDate",v)} type="date"/></Field><Field label="Received By *" full><Input value={f.receivedBy} onChange={v=>set("receivedBy",v)} placeholder="Full name"/></Field>
  </div></Modal>
}
