import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function RegisterPackaging({close,state,update,notify}) {
  const [f,setF]=useState({name:"",type:"",description:"",qty:"",unit:"",supplier:"",po:"",receiptDate:today(),warehouse:"",recipient:"",notes:""});
  const set=(k,v)=>setF(x=>({...x,[k]:v})); const submit=()=>{for(const [k,l] of Object.entries({name:"Name",qty:"Quantity",supplier:"Supplier",receiptDate:"Receipt Date",recipient:"Recipient"}))if(!f[k])return notify(l+" is required.","error");const rid=id("PKG",state.counters.pkg);update(s=>{s.packagings.push({id:"PKG-"+Date.now(),receiptId:rid,...f});s.counters.pkg++});close();notify("Packaging registered successfully!")};
  return <Modal title="Register Packaging" sub={`Receipt ID: ${id("PKG",state.counters.pkg)}`} open onClose={close} wide footer={<><Button onClick={close}>Cancel</Button><Button variant="primary" onClick={submit}>✓ Register Packaging</Button></>}><div className="form-grid">
    <div className="fsec">Packaging Details</div><Field label="Name *"><Input value={f.name} onChange={v=>set("name",v)} placeholder="Aluminium Blister Foil"/></Field><Field label="Type *"><Select value={f.type} onChange={v=>set("type",v)} options={["Primary","Secondary","Tertiary","Labeling","Other"]}/></Field><Field label="Description" full><textarea value={f.description} onChange={e=>set("description",e.target.value)}/></Field><div className="fsec">Quantity & Unit</div><Field label="Quantity *"><Input value={f.qty} onChange={v=>set("qty",v)} type="number"/></Field><Field label="Unit"><Select value={f.unit} onChange={v=>set("unit",v)} options={state.opts.unit}/></Field><div className="fsec">Supplier & Receipt</div><Field label="Supplier *"><Select value={f.supplier} onChange={v=>set("supplier",v)} options={state.opts.supplier}/></Field><Field label="PO No."><Input value={f.po} onChange={v=>set("po",v)}/></Field><Field label="Receipt Date *"><Input value={f.receiptDate} onChange={v=>set("receiptDate",v)} type="date"/></Field><Field label="Warehouse"><Select value={f.warehouse} onChange={v=>set("warehouse",v)} options={state.opts.warehouse}/></Field><Field label="Recipient *"><Input value={f.recipient} onChange={v=>set("recipient",v)}/></Field><Field label="Notes" full><textarea value={f.notes} onChange={e=>set("notes",e.target.value)}/></Field>
  </div></Modal>
}
