import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { MaterialView } from './MaterialView';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function Storekeeper({state,update,notify,tab,setTab,search,setSearch,open,selected,setSelected,addOption}) {
  const materials=state.materials.filter(m=>!search||`${m.materialName} ${m.receiptId} ${m.supplierBatch}`.toLowerCase().includes(search.toLowerCase()));
  const packaging=state.packagings.filter(p=>!search||`${p.name} ${p.receiptId} ${p.supplier}`.toLowerCase().includes(search.toLowerCase()));
  const stats=[["Total Materials",state.materials.length,"Registered"],["In Quarantine",state.materials.filter(m=>m.status==="Quarantine").length,"Pending release"],["Sampling Requested",state.materials.filter(m=>m.samplingStatus==="Sampling Requested").length,"Awaiting sampler"],["Released",state.materials.filter(m=>m.status==="Released").length,"QC approved"]];
  return <>
    <Tabs value={tab} onChange={x=>{setTab(x);setSearch("")}} items={[["materials","▦ Raw Materials"],["packaging","▣ Packaging"]]}/>
    {tab==="materials"?<Page title="Raw Materials" sub="All registered raw materials" action={<Button variant="primary" onClick={()=>open("register")}>＋ Register Material</Button>}>
      {state.notifications.filter(n=>!n.read).map(n=><div className="notif-banner" key={n.id}>🎉 <div><b>{n.title}</b><small>{n.message}</small></div><button onClick={()=>update(s=>{const x=s.notifications.find(x=>x.id===n.id);if(x)x.read=true})}>×</button></div>)}
      <div className="stats-row">{stats.map(([a,b,c])=><div className="stat-card" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>
      <div className="table-card"><Toolbar search={search} setSearch={setSearch} placeholder="Search materials…"><select><option>All Statuses</option></select></Toolbar><div className="table-wrap"><table><thead><tr>{["Receipt ID","Material Name","Sup. Batch No.","Receiving Date","Total Qty","Status","Sampling Status","Expire Date","Actions"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>
      {materials.map(m=><tr key={m.id}><td className="mono">{m.receiptId}</td><td><b>{m.materialName}</b><small>{m.category}</small></td><td className="mono">{m.supplierBatch}</td><td>{fmt(m.receiptDate)}</td><td>{m.totalQty} {m.unit}</td><td><Status value={m.status}/></td><td><Status value={m.samplingStatus}/></td><td>{fmt(m.expDate)}</td><td><Button small onClick={()=>{setSelected(m);open("materialView")}}>View</Button>{m.status==="Released"&&<Button small variant="purple" onClick={()=>{setSelected(m);open("releaseLabel")}}>Label</Button>}</td></tr>)}
      </tbody></table>{!materials.length&&<Empty text="No materials registered yet"/>}</div></div>
    </Page>:<Page title="Packaging" sub="All registered packaging materials" action={<Button variant="primary" onClick={()=>open("packaging")}>＋ Register Packaging</Button>}>
      <div className="stats-row">{[["Total Packaging",state.packagings.length,"Registered"],["Types",new Set(state.packagings.map(x=>x.type).filter(Boolean)).size,"Distinct types"],["Total Qty",state.packagings.reduce((a,x)=>a+(+x.qty||0),0).toLocaleString(),"Combined units"],["Suppliers",new Set(state.packagings.map(x=>x.supplier).filter(Boolean)).size,"Distinct suppliers"]].map(x=><div className="stat-card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</div>
      <div className="table-card"><Toolbar search={search} setSearch={setSearch} placeholder="Search packaging…"/><div className="table-wrap"><table><thead><tr>{["Receipt ID","Name","Type","Description","Qty","Supplier","Receipt Date","Warehouse","Sampling","Actions"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{packaging.map(p=><tr key={p.id}><td className="mono">{p.receiptId}</td><td><b>{p.name}</b></td><td><Badge kind="packaging">{p.type}</Badge></td><td>{p.description||"—"}</td><td>{p.qty} {p.unit}</td><td>{p.supplier}</td><td>{fmt(p.receiptDate)}</td><td>{p.warehouse||"—"}</td><td><Status value={p.samplingStatus||"Not Sampled"}/></td><td><Button small onClick={()=>{setSelected(p);open("packagingView")}}>View</Button>{(!p.samplingStatus||p.samplingStatus==="Not Sampled")&&<Button small variant="primary" onClick={()=>{update(s=>{const x=s.packagings.find(x=>x.id===p.id);x.samplingStatus="Sampling Requested";s.samples.push({id:"PKGSMP-"+Date.now(),sampleId:"PKG-SMP-"+Date.now(),materialName:p.name+" (Packaging)",receiptId:p.receiptId,supplierBatch:"PKG",supplier:p.supplier,manufacturer:"",expDate:"",receiptDate:p.receiptDate,batchSize:p.qty,unit:p.unit,sampleSize:"",containers:"",sampler:"",storage:"",samplingDate:"",testingStatus:"Not Tested",sampleType:"Packaging"})});notify("Sampling requested for packaging: "+p.name)}}>Sample</Button>}</td></tr>)}</tbody></table>{!packaging.length&&<Empty text="No packaging registered yet"/>}</div></div>
    </Page>}
  </>
}
