# Generated by Django 4.2.11 on 2026-08-22 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_role", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
