import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function Analyst({state,update,notify,page,setPage,search,setSearch,open,setSelected}) {
  if(page==="home") return <div className="analyst-home"><div className="analyst-launcher">
    {[["monograph","📖","Monograph","Manage material specifications","0 Monographs"],["samples","🧪","Samples","View & start testing",`${state.samples.filter(s=>s.testingStatus==="Not Tested").length+state.fpSamples.filter(s=>s.testingStatus==="Not Tested").length} Pending`],["certificates","📋","Certificates","COA management",`${state.coas.length} COAs`]].map(x=><button className="launch-card" key={x[0]} onClick={()=>setPage(x[0])}><div>{x[1]}</div><b>{x[2]}</b><small>{x[3]}</small><span>{x[4]}</span></button>)}
  </div></div>;
  if(page==="samples") return <Page title="Samples" sub="Samples received from the sampling team" action={<Button onClick={()=>setPage("home")}>← Back</Button>}><div className="table-card"><Toolbar search={search} setSearch={setSearch}/><Table headers={["Receipt ID","Sample","Batch","Receipt Date","Sample Qty","Containers","Sampling Date","Sampler","Expiry","Testing","Actions"]}>{[...state.samples,...state.fpSamples.map(x=>({...x,receiptId:x.sampleId,materialName:x.productName+" ("+x.productType+")",supplierBatch:x.batchNo,receiptDate:x.samplingDate,containers:"1",sampler:"—",samplingDate:x.samplingDate,expDate:x.expDate}))].filter(s=>!search||`${s.materialName} ${s.receiptId}`.toLowerCase().includes(search.toLowerCase())).map(s=><tr key={s.id}><td>{s.receiptId}</td><td><b>{s.materialName}</b></td><td>{s.supplierBatch}</td><td>{fmt(s.receiptDate)}</td><td>{s.sampleSize} {s.unit}</td><td>{s.containers}</td><td>{fmt(s.samplingDate)}</td><td>{s.sampler}</td><td>{fmt(s.expDate)}</td><td><Status value={s.testingStatus}/></td><td>{s.testingStatus!=="Completed"&&<Button small variant={s.testingStatus==="In Testing"?"warning":"primary"} onClick={()=>{setSelected(s);open("coaForm")}}>{s.testingStatus==="In Testing"?"Continue COA":"Start Testing"}</Button>}</td></tr>)}</Table></div></Page>;
  return <Page title="Certificates of Analysis" sub="All created COAs and their approval status" action={<Button onClick={()=>setPage("home")}>← Back</Button>}><div className="table-card"><Toolbar search={search} setSearch={setSearch}/><Table headers={["COA ID","Sample Name","Batch","Analyst","Created Date","Status","Actions"]}>{state.coas.filter(c=>!search||`${c.sampleName} ${c.receiptId} ${c.batchNo}`.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id}><td className="mono">{c.id}</td><td>{c.sampleName}</td><td>{c.batchNo}</td><td>{c.analyst}</td><td>{fmt(c.createdDate)}</td><td><Status value={c.status}/></td><td><Button small onClick={()=>{setSelected(c);open("coaView")}}>View</Button></td></tr>)}</Table></div></Page>
}
