import { useState } from 'react';
import { Badge, Status, Button, Modal, Field, Input, Select, Table, Empty } from '../../../../components/ui';
import { Tabs, Page, Toolbar } from '../../../../components/layout';
import { Detail } from '../shared/Detail';
import { formatDate as fmt, today, createDocumentId as id } from '../../../../utils';
export function COAForm({sample,close,state,update,notify}) {
  const m=state.materials.find(x=>x.id===sample?.materialId);const [f,setF]=useState({specsCode:"",reference:"",analyst:"",analysisDate:today(),remarks:""});
  if(!sample)return null; const name=sample.productName?`${sample.productName} (${sample.productType})`:sample.materialName;
  const submit=()=>{for(const [k,l] of Object.entries({specsCode:"Specs Code",reference:"Reference",analyst:"Analyst Name"}))if(!f[k])return notify(l+" is required.","error");const cid=id("COA",state.counters.coa);update(s=>{s.coas.push({id:cid,sampleId:sample.id,materialId:sample.materialId,receiptId:sample.receiptId||sample.sampleId,sampleName:name,batchNo:sample.batchNo||sample.supplierBatch||"—",batchSize:sample.batchSize||"—",supplier:sample.supplier||m?.supplier||"—",manufacturer:sample.manufacturer||m?.manufacturer||"—",mfgDate:sample.mfgDate||m?.mfgDate||"",expDate:sample.expDate||m?.expDate||"",receivedDate:sample.receiptDate||sample.samplingDate||"",...f,status:"Draft",createdDate:today(),qcManagerComment:""});s.counters.coa++;const src=s.fpSamples.find(x=>x.id===sample.id);if(src)src.testingStatus="Completed";const rm=s.samples.find(x=>x.id===sample.id);if(rm)rm.testingStatus="Completed"});close();notify("COA created successfully!")};
  return <Modal title="Create Certificate of Analysis" sub={`${sample.sampleId||sample.receiptId} · ${name}`} open onClose={close} wide footer={<><Button onClick={close}>Cancel</Button><Button variant="primary" onClick={submit}>✓ Create & Open COA</Button></>}><div className="form-grid"><div className="fsec">Material & Sample Data</div>{[["Sample Name",name],["Batch No.",sample.batchNo||sample.supplierBatch],["Batch Size",sample.batchSize],["Supplier",sample.supplier||m?.supplier],["Manufacturer",sample.manufacturer||m?.manufacturer],["Manufacturing Date",fmt(sample.mfgDate||m?.mfgDate)],["Expiry Date",fmt(sample.expDate||m?.expDate)],["Received Date",fmt(sample.receiptDate||sample.samplingDate)]].map(x=><Field label={x[0]} key={x[0]}><Input value={x[1]||"—"} readOnly/></Field>)}<div className="fsec">Analyst Input</div><Field label="Specs Code *"><Input value={f.specsCode} onChange={v=>setF(x=>({...x,specsCode:v}))}/></Field><Field label="Reference *"><Select value={f.reference} onChange={v=>setF(x=>({...x,reference:v}))} options={["BP 2025","USP","EP","JP","In-House"]}/></Field><Field label="Analyst Name *"><Input value={f.analyst} onChange={v=>setF(x=>({...x,analyst:v}))}/></Field><Field label="Analysis Date"><Input value={f.analysisDate} onChange={v=>setF(x=>({...x,analysisDate:v}))} type="date"/></Field><Field label="Remarks" full><textarea value={f.remarks} onChange={e=>setF(x=>({...x,remarks:e.target.value}))}/></Field></div></Modal>
}
