# Generated by Django 4.2.16 on 2026-08-13 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("LOGIN", "LOGIN"),
                            ("LOGOUT", "LOGOUT"),
                            ("LOGIN_FAILED", "LOGIN_FAILED"),
                            ("ROLE_CHANGE", "ROLE_CHANGE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("record_type", models.CharField(max_length=50)),
                ("record_id", models.CharField(max_length=50)),
                ("field_changes", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
