# Generated by Django 4.2.11 on 2026-08-22 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=100)),
                ("action_type", models.CharField(max_length=50)),
                ("module", models.CharField(max_length=50)),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("entity_id", models.CharField(blank=True, max_length=50)),
                ("before_values", models.JSONField(blank=True, null=True)),
                ("after_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
