# Generated by Django 4.2.11 on 2026-08-22 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectronicSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("signer_printed_name", models.CharField(max_length=100)),
                (
                    "meaning",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("reviewed", "Reviewed"),
                            ("completed", "Completed"),
                            ("released", "Released"),
                        ],
                        max_length=20,
                    ),
                ),
                ("record_type", models.CharField(max_length=50)),
                ("record_id", models.CharField(max_length=50)),
                ("comment", models.TextField(blank=True, default="")),
            ],
        ),
    ]
