# Generated by Django 4.2.11 on 2026-08-22 19:56

from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receipt_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("material_name", models.CharField(db_index=True, max_length=100)),
                ("supplier", models.CharField(max_length=100)),
                ("supplier_batch", models.CharField(max_length=50)),
                ("exp_date", models.DateField()),
                ("receipt_date", models.DateField()),
                ("received_by", models.CharField(max_length=100)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("QUARANTINE", "Quarantine"),
                            ("SAMPLING_REQUESTED", "Sampling Requested"),
                            ("SAMPLED", "Sampled"),
                            ("UNDER_ANALYSIS", "Under Analysis"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CERTIFICATE_DRAFT", "Certificate Draft"),
                            ("CERTIFICATE_UNDER_REVIEW", "Certificate Under Review"),
                            ("CERTIFICATE_APPROVED", "Certificate Approved"),
                            ("CERTIFICATE_LOCKED", "Certificate Locked"),
                            ("RELEASED", "Released"),
                        ],
                        default="QUARANTINE",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("qc_number", models.CharField(blank=True, max_length=20)),
                ("qc_sign", models.CharField(blank=True, max_length=100)),
                ("retest_date", models.DateField(blank=True, null=True)),
                ("released_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
